version: '3.9'

services:
  nginx-service:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-service
    depends_on:
      - php-service
    networks:
      - exads-network

  php-service:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: php8-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    restart: always
    environment:
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_NAME}"
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    networks:
      - exads-network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  exads-network:
